### ISSUE TITLE
Unable to save in RaceRoom Racing Experience Install 2 when also having RaceRoom Racing Experience

### ISSUE THREAD

**Issue by Karting06** [hiboudev/R3E-HUD-Manager#1]
It could be nice if you were able to choose the R3E saved directory. 
(It could be useful for beta testers ;) )

**Comment by hiboudev** [comment]
OK, actually the application searches for the first directory that has a valid value in "GameInstallDir.ini". Cause I thought that only one can be valid.
So you say that several directories can be valid? If so I can add a list component to choose the current directory to use between the valid ones. :)

**Comment by Karting06** [comment]
For the majority of users, only can be valid, yes. 
But for betatesters, multiple can be valid, yes ^^ (You don't have to give a high priority on this one ;) ).

**Comment by hiboudev** [comment]
Fixed in this commit: https://github.com/hiboudev/R3E-HUD-Manager/commit/a21b3910bc6a7519ac25f33a8cede30bbd11ffaa
The directory menu only shows (bottom left) if you have several R3E directories.
When you change directory, app doesn't automatically load the new hud, but the directory will be used in further loads and writes.

**Comment by Karting06** [comment]
Ok thank you ;)
